name: Deploy VitePress + DocC to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'Sources/**'
      - 'Package.swift'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: write   # gh-pages 브랜치 푸시에 필요
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 1) DocC 빌드 (macOS)
  build_docc:
    runs-on: macos-15
    steps:
      - name: 📥 Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Select Xcode 16.4 (Swift 6.1)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: 🔎 Verify Package.swift
        run: |
          ls -la
          test -f Package.swift || (echo "❌ Package.swift not found at repo root"; exit 1)

      - name: 🧱 Build DocC → site/docc/
        run: |
          rm -rf site
          mkdir -p site/docc
          swift package \
            --allow-writing-to-directory site/docc \
            generate-documentation \
            --target WeaveDI \
            --output-path site/docc \
            --transform-for-static-hosting \
            --hosting-base-path /WeaveDI/docc
          # DocC 인덱스 리다이렉트(편의)
          cat > site/docc/index.html <<'HTML'
          <!DOCTYPE html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./documentation/weavedi/">
          <link rel="canonical" href="./documentation/weavedi/">
          HTML
          touch site/docc/.nojekyll

      - name: 📦 Upload DocC artifact
        uses: actions/upload-artifact@v4
        with:
          name: docc-site
          path: site/docc
          if-no-files-found: error
          retention-days: 3

  # 2) VitePress 빌드 (Ubuntu)
  build_vitepress:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            docs/**

      - name: 📦 Install deps
        run: npm ci

      - name: 🧹 Clean
        run: rm -rf docs/.vitepress/dist docs/.vitepress/cache

      - name: 🏗️ Build VitePress → site/
        env:
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
          VP_IGNORE_DEAD_LINKS: '1'   # 문서 작성 중엔 임시 허용, 완성 후 제거 권장
        run: |
          npm run docs:build
          mkdir -p site
          cp -a docs/.vitepress/dist/* site/
          touch site/.nojekyll

      - name: 📦 Upload VitePress artifact
        uses: actions/upload-artifact@v4
        with:
          name: vitepress-site
          path: site
          if-no-files-found: error
          retention-days: 3

  # 3) 병합 & gh-pages 배포 (git push 방식 — 콜론 파일 허용)
  merge_and_deploy:
    needs: [build_docc, build_vitepress]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download VitePress
        uses: actions/download-artifact@v4
        with:
          name: vitepress-site
          path: site

      - name: 📥 Download DocC (into /docc)
        uses: actions/download-artifact@v4
        with:
          name: docc-site
          path: site/docc

      - name: 🗂️ List merged output
        run: |
          echo "== site tree =="
          find site -maxdepth 2 -type d -print

      # gh-pages 브랜치로 직접 커밋/푸시 → Pages가 이 브랜치를 서빙
      - name: 🚀 Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
          force_orphan: true  # 깔끔한 단일 히스토리
          commit_message: "docs: publish VitePress + DocC"

      - name: ✅ Summary
        run: |
          echo "## 🚀 Deployed via gh-pages branch!" >> $GITHUB_STEP_SUMMARY
          echo "Main (VitePress): https://roy-wonji.github.io/WeaveDI/" >> $GITHUB_STEP_SUMMARY
          echo "DocC:            https://roy-wonji.github.io/WeaveDI/docc/" >> $GITHUB_STEP_SUMMARY
