name: Build DocC and Deploy (gh-pages)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0.0"
      # ✅ 요청대로 유지
      - name: Set up Swift 6.1
        uses: fwal/setup-swift@v2
        with:
          swift-version: "6.1.0"

      - name: Generate DocC
        env:
          SCHEME_NAME: DiContainer            # 실제 스킴(=제품명)과 일치해야 함
          DESTINATION: generic/platform=macOS # macOS가 안전
          IS_USER_SITE: "false"
          HOSTING_BASE_PATH: ${{ github.event.repository.name }} # → DiContainer
        run: |
          chmod +x ./GENERATE_DOCS.sh
          ./GENERATE_DOCS.sh

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
