name: Documentation (DocC → GitHub Pages)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.4 (Swift 6.1)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Show toolchain versions
        run: |
          xcodebuild -version
          swift --version

      - name: Build DocC (WeaveDI → docs/)
        run: |
          rm -rf docs
          swift package \
            --allow-writing-to-directory docs \
            generate-documentation \
            --target WeaveDI \
            --output-path docs \
            --transform-for-static-hosting \
            --hosting-base-path /WeaveDI
          touch docs/.nojekyll
          cat > docs/index.html <<'HTML'
          <!DOCTYPE html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./documentation/weavedi/">
          <link rel="canonical" href="./documentation/weavedi/">
          HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
