name: Documentation
on:
  push:
    branches: [main]
  workflow_dispatch:

# ✅ GITHUB_TOKEN로 gh-pages에 push하려면 필요
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.4 (Swift 6.1)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build DocC
        run: |
          rm -rf docs-out
          mkdir -p docs-out
          swift package \
            --allow-writing-to-directory docs-out \
            generate-documentation \
            --target DiContainer \
            --output-path docs-out \
            --transform-for-static-hosting \
            --hosting-base-path /DiContainer
          touch docs-out/.nojekyll
          cat > docs-out/index.html <<'HTML'
          <!DOCTYPE html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./documentation/dicontainer/">
          <link rel="canonical" href="./documentation/dicontainer/">
          HTML

      - name: Publish to GitHub Pages (gh-pages)
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
          clean: true                # ✅ 기존 파일 정리
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          token: ${{ secrets.GITHUB_TOKEN }}   # 보통 자동 주입되지만 명시하면 확실
