# .github/workflows/docs.yml
name: Documentation

on:
  release:
    types: [published]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      # ✅ Xcode 16.4 (Swift 6.1) 선택
      - name: Select Xcode 16.4 (Swift 6.1)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Show toolchain versions
        run: |
          xcodebuild -version
          swift --version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages (output dir)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: docs-out

      - name: Build DocC
        run: |
          rm -rf docs-out/.git
          rm -rf docs-out/*
          swift package \
            --allow-writing-to-directory docs-out \
            generate-documentation \
            --target DiContainer \
            --output-path docs-out \
            --transform-for-static-hosting \
            --hosting-base-path /DiContainer
          # Jekyll 무시 + 루트 리다이렉트 권장
          touch docs-out/.nojekyll
          cat > docs-out/index.html <<'HTML'
          <!DOCTYPE html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./documentation/dicontainer/">
          <link rel="canonical" href="./documentation/dicontainer/">
          HTML

      - name: Fix permissions
        run: sudo chown -R $USER docs-out

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
